language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: CMAKE_BUILD_TYPE=Release
    - os: osx
      osx_image: xcode9.4
      env: CMAKE_BUILD_TYPE=Release

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                 ;fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq   ;fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      brew install qt quazip;
      export PATH="$(brew --prefix qt)/bin:$PATH";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y git cmake qtbase5-dev qt5-default qtdeclarative5-dev qtbase5-private-dev libqt5svg5-dev qtmultimedia5-dev libqt5x11extras5-dev qttools5-dev libqt5webkit5-dev libqt5opengl5-dev libqt5xmlpatterns5-dev libquazip-dev zlib1g-dev python3-dev libpythonqt-dev libx11-dev mesa-common-dev libqt4-dev qtmobility-dev python2.7-dev ;fi
before_script:
  - mkdir build-qt5 build-qt4
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      cd build-qt4;
      cmake .. -DQT_USE_QT5=OFF -DPYTHON_USE_PYTHON3=OFF;
      make;
      cd ..;
      sudo apt-get purge -y libpythonqt-dev libpythonqt2.1;
    fi
  - cd build-qt5
  - git clone https://github.com/Orochimarufan/PythonQt
  - cd PythonQt/build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      git checkout 18d4c24;
      sudo cp -r /usr/include/python2.7 ./pythonincludes;
      sudo chmod 777 ./pythonincludes;
      curl https://trac.macports.org/raw-attachment/ticket/44288/patch-Include-pyport.h.diff | patch ./pythonincludes/pyport.h;
      cmake .. -DCMAKE_PREFIX_PATH="$(brew --prefix qt)" -DPYTHON_INCLUDE_DIR=./pythonincludes -DPythonQt_Python3=OFF -DBUILD_SHARED_LIBS=ON;
    else
      git checkout ea98dd0;
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DPythonQt_Python3=ON -DBUILD_SHARED_LIBS=ON;
    fi
  - sudo make install
  - cd ../..
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cmake ..  -DCMAKE_PREFIX_PATH="$(brew --prefix qt)" -DPYTHON_USE_PYTHON3=OFF -DPYTHON_INCLUDE_DIR=./PythonQt/build/pythonincludes -DPYTHONQT_LIBRARY=/usr/local/lib/libQt5Python27.dylib -DPYTHONQT_INCLUDE_DIR=/usr/local/include/Qt5Python27/PythonQt -DPYTHONQT_QTALL_LIBRARY=/usr/local/lib/libQt5Python27_QtAll.dylib -DPYTHONQT_QTALL_INCLUDE_DIR=/usr/local/include/Qt5Python27/PythonQt;
    else
      sudo ln -s /usr/lib/libQt5Python34_QtAll.so /usr/lib/libQtPython_QtAll.so;
      sudo ln -s /usr/lib/libQt5Python34.so /usr/lib/libQtPython.so;
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr;
    fi
  - make

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        sudo make install DESTDIR=.;
        mv screencloud.app ScreenCloud.app;
        macdeployqt ScreenCloud.app -dmg -verbose=3
        export DEPLOYFILE=ScreenCloud.dmg;
    else
        make install DESTDIR=.;
        cd ..;
        wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
        chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
        unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH;
        ./linuxdeployqt-continuous-x86_64.AppImage build-qt5/usr/share/applications/*.desktop -bundle-non-qt-libs;
        ./linuxdeployqt-continuous-x86_64.AppImage build-qt5/usr/share/applications/*.desktop -appimage;
        export DEPLOYFILE=ScreenCloud-x86_64.AppImage;
    fi

deploy:
  provider: releases
  api_key:
    secure: xY0hOHsO6oztTs/fyKAl4FrA+6ylke3QXsAHzntIEHOt7sgVGQW/4QzJQYPwmAQAkVOssjZWdaJrFXQMFw+lYUpwZGSycPB+fDnosKYlxXFHG4rIliyG+az6ODzA0YeugFwlYAcHXx1qzBJ8gh3tHhB16ur7OQ62VdunCpG7NDtaINGMojzL4DmSfyiyOMPM4p6EcD+qaKd6dxBePXkmZ5J+YOvgfLcd1mJ94V7+WnQ66KltIaFZPewaansw/p6KAUxPXcTMyMepjcjQFQyucs4rN+9EmAaA5d0rzaucbTra1nJbJel0qWC+hcH8WF86ez8nTPFY1MGjRPZmfFGesvwUkzc3IH2w5j82BmP5x7IP+TZQ4qddM/eeWIX4WeTUKoVHHt/+iZNe6kZ7Qv8ZEzQS8/G0WHz0AyoWCKSztMFBs2XZvLPjEjhCr1HKH8ueX2zXFVRf9mpp23kjGyLzacTzSC+6xjrcp27s/fY+NH3kXw67c2tB815BqtYvWMoEZVNF1+7v0nbBOs6SaDAErLqRKOP4GKgEG+J3GvokuVmQpSzwk+v4EX4ixJm3pI6C+yFaDRc7CEtkXRFIPxesMeP2w8thIuWWNaNzRAKlxR4Dx9h4bLunsx5HDfwA9h0CszcOU2ewvrR60QExZ7fjTrIoqC/UWwjoCqFv+TlyGLU=
  file: $DEPLOYFILE
  skip_cleanup: true
  on:
    repo: olav-st/screencloud
    tags: true
