name: screencloud
version: "1.4.0"
summary: Easy to use screenshot sharing application
description: Take a screenshot using one of the 3 hotkeys or simply click the ScreenCloud tray icon. You can choose where you want to save your screenshot.
confinement: devmode
grade: devel
base: core18

apps:
  screencloud:
    command: desktop-launch screencloud.sh
    plugs: 
      - x11
      - wayland
      - network
      - home
      - opengl
      - pulseaudio
      - desktop
      - gsettings
      - network-bind #A local port is used to check if another screencloud process is running 

parts:
  screencloud:
    source: https://github.com/olav-st/screencloud.git
    source-tag: master
    plugin: cmake
    build-packages:
      - g++
      - qtbase5-private-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - qtmultimedia5-dev
      - libquazip5-dev
      - libpythonqt-qt5-python3-dev
      - libpythonqt-qtall-qt5-python3-dev
      - python3-dev
    stage-packages:
      - openssl
      - libqt5concurrent5
      - libqt5x11extras5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libglib2.0-bin
      - dconf-gsettings-backend
      - libquazip5-1
      - libpythonqt-qt5-python3-3
      - libpythonqt-qtall-qt5-python3-3
      - libpython3-stdlib
      - python3-paramiko # For the SFTP plugin
    after: [desktop-qt5]
